In [ ]:
## Creating the manual dataset around 250 flirty messages

In [4]:
import pandas as pd
flirty_messages=[
    "You looked really cute today.",
    "That smile of yours is dangerous 😍",
    "How do you manage to look so good every time?",
    "I have to admit, you're pretty attractive.",
    "Your voice is honestly so nice.",
    "You looked good in that picture, not gonna lie.",
    "Why are you looking this cute today?",
    "I could listen to you talk for hours.",
    "Your smile is becoming my favourite thing.",
    "You have really beautiful eyes.",
    "You looked so good that I forgot what I was saying.",
    "I like the way you laugh.",
    "You have no idea how charming you are.",
    "That outfit really suits you.",
    "You're looking extra handsome today.",
    "I wasn't expecting you to be this cute.",
    "Your pictures don't do you justice.",
    "You have a very attractive way of talking.",
    "I think your smile could fix my mood instantly.",
    "You're honestly hard not to notice.",
    "I like how confident you are.",
    "You look even better in person.",
    "I was trying to focus, then your photo appeared.",
    "You're becoming a little too attractive for my peace of mind.",
    "You have such a lovely face.",
    "Your laugh is ridiculously cute.",
    "I think you know how good you look.",
    "That look suits you way too well.",
    "You have a really nice energy about you.",
    "How can someone be this cute and act normal?",
    "I caught myself smiling at your picture.",
    "You looked lovely today, by the way.",
    "You have a very distracting smile.",
    "I think you just raised my standards.",
    "You're exactly the kind of person I'd notice in a crowd.",
    "Are you always this charming, or is it just with me?",
    "Stop being cute. I'm trying to concentrate.",
    "Are you flirting with me right now? 👀",
    "If you keep talking like that, I'll get ideas.",
    "You really enjoy making me blush, don't you?",
    "Is making me smile your full-time job?",
    "You're becoming my favourite distraction.",
    "I was going to tease you, but you're too cute today.",
    "Should I be worried about how much I like talking to you?",
    "You can't just say that and expect me to act normal.",
    "You're lucky your smile is so convincing.",
    "I see someone is trying to impress me.",
    "Don't tempt me to flirt back.",
    "You know exactly how to get my attention.",
    "I think you're secretly trying to win me over.",
    "You're making it difficult to play it cool.",
    "One more compliment and I'll start expecting them.",
    "I was perfectly fine before your message arrived.",
    "You enjoy getting a reaction out of me, don't you?",
    "I can't decide whether to roll my eyes or smile.",
    "You're a little too good at this flirting thing.",
    "I should probably stop smiling at my phone because of you.",
    "Is that your way of saying you miss me?",
    "You seem very interested in keeping me distracted.",
    "I think you like making me nervous.",
    "You're making this crush very difficult to hide.",
    "If I flirt back, don't act surprised.",
    "I was going to act mysterious, but then you texted.",
    "You're trouble, and I might like that.",
    "How am I supposed to ignore you when you're like this?",
    "You make flirting seem suspiciously easy.",
    "I think we both know what you're doing here.",
    "You're getting dangerously close to becoming my favourite person.",
    "Don't smile at me like that unless you mean it.",
    "I hope you realise I'm flirting with you too.",
    "I was hoping you'd message me today.",
    "Your name popping up on my phone makes me smile.",
    "I was just thinking about you.",
    "I like talking to you more than I expected.",
    "I keep finding excuses to text you.",
    "I wonder if you smile at my messages too.",
    "I was about to text you, and then you appeared.",
    "I kind of missed talking to you today.",
    "I like how our conversations never feel forced.",
    "I wish our chats lasted a little longer.",
    "I may have reread your message a few times.",
    "Talking to you has become my favourite part of the day.",
    "I think I have a favourite notification now.",
    "I keep checking whether you're online.",
    "I wish I could hear your voice instead of reading your texts.",
    "I didn't expect to look forward to your messages this much.",
    "I was having an ordinary day until you texted.",
    "I wonder what you're doing right now.",
    "I wish you were here instead of just on my screen.",
    "You make even boring conversations fun.",
    "I keep catching myself wondering how your day went.",
    "I think I miss our conversations more than I should.",
    "I like being the person you choose to message.",
    "I was waiting for your reply, actually.",
    "You have a habit of staying on my mind.",
    "I like the little butterflies I get when you text.",
    "I could talk to you all night.",
    "I was smiling at my phone, and someone noticed.",
    "You make texting unexpectedly exciting.",
    "I wish I could steal five more minutes with you.",
    "I like hearing from you, even when I have nothing important to say.",
    "I think about you at the most random times.",
    "I was hoping we'd get a chance to talk today.",
    "Your messages make my day a little better.",
    "I don't think you realise how often you cross my mind.",
    "I think I'm starting to like you.",
    "I have a little crush on you, in case it wasn't obvious.",
    "I like you as more than just a friend.",
    "I've been wanting to tell you that I find you attractive.",
    "I wonder if you feel this spark too.",
    "I think there's something special between us.",
    "I'd be lying if I said I didn't have feelings for you.",
    "I keep hoping you'll ask me out.",
    "I get nervous around you because I like you.",
    "I think I like you more than I planned to.",
    "I want to know if you see me romantically too.",
    "I think we'd make a cute couple.",
    "I don't want to keep hinting, so yes, I like you.",
    "I feel something different when I'm around you.",
    "I would say yes if you asked me out.",
    "I think we should find out where this chemistry goes.",
    "I like you enough to risk making this awkward.",
    "I want to stop guessing and ask if you like me too.",
    "I don't think this is just friendship for me anymore.",
    "I'm interested in you, and I'd like to know you better.",
    "Would it be too forward if I said I find you attractive?",
    "I want to be honest: I have feelings for you.",
    "I think you might be becoming someone special to me.",
    "I hope you know I'm serious when I flirt with you.",
    "I keep imagining what a date with you would be like.",
    "I think I'd regret it if I never told you I liked you.",
    "I like you, and I'd love to know if the feeling is mutual.",
    "I think there's a reason I keep looking for you in a room.",
    "I feel drawn to you in a way I can't explain.",
    "I like the idea of being someone special to you.",
    "I'm trying not to develop a crush, but you're not helping.",
    "I think you're becoming more than just a casual thought.",
    "I want to know what this connection could become.",
    "I like you, and I hope that makes you smile.",
    "If I asked you out, would you say yes?",
    "I couldn't stop smiling after seeing you today.",
    "I think our eye contact lasted a little too long.",
    "I nearly forgot what I was saying when you smiled at me.",
    "I wanted to sit closer to you today.",
    "I noticed you looking at me, and I liked it.",
    "I wish our goodbye hug had lasted longer.",
    "I caught you staring, and honestly, I wasn't complaining.",
    "I was hoping you'd sit next to me.",
    "I kept looking for you across the room.",
    "You make me nervous just by standing beside me.",
    "I liked how close we were standing earlier.",
    "I wanted to find a reason to keep talking to you.",
    "I think we both noticed that little spark.",
    "You make it difficult to act normal when you're nearby.",
    "I was secretly hoping you'd come talk to me.",
    "That little look you gave me is still on my mind.",
    "I think we were both finding excuses not to leave.",
    "I liked the way you leaned closer when we talked.",
    "I wanted to hold your hand, but I wasn't sure if you'd want that.",
    "You made a crowded room feel like it was just us.",
    "I was hoping you'd notice that I dressed up today.",
    "I like how naturally I end up standing next to you.",
    "I wanted to ask you to stay a little longer.",
    "You made saying goodbye harder than it needed to be.",
    "I was trying to play it cool, but I think you noticed.",
    "I liked the way you looked at me today.",
    "I wish we'd had a little more time alone together.",
    "I wanted to tell you how good you looked, but I got shy.",
    "I think I'd blush if you said that to me in person.",
    "I was more aware of you than anyone else there.",
    "I wish I could give you a long hug right now.",
    "I'd love to spend a quiet evening with you.",
    "I want to hold your hand while we walk together.",
    "I think cuddling with you would be dangerously comforting.",
    "I'd love to watch the sunset with you.",
    "I wish I could fall asleep beside you and wake up next to you.",
    "I'd love to cook dinner for you sometime.",
    "I want to steal your hoodie and never give it back.",
    "I'd happily spend a rainy day curled up with you.",
    "I want to make you smile after a difficult day.",
    "I think your hugs would fix a lot of my bad days.",
    "I'd love to kiss you goodnight someday.",
    "I want to be the person who makes you feel adored.",
    "I'd choose your company over a fancy plan any day.",
    "I want to sit close enough that our shoulders touch.",
    "I'd love to dance with you, even if there's no music.",
    "I think holding you would feel like coming home.",
    "I'd like to be your favourite person to hug.",
    "I want to make ordinary moments feel special with you.",
    "I'd love to have you beside me for all the little moments.",
    "I wish I could tell you this while looking into your eyes.",
    "I'd love to share my favourite songs with you.",
    "I want to be the person you lean on when you're tired.",
    "I'd love to spend a lazy Sunday with you.",
    "I want to learn all the little things that make you happy.",
    "I'd happily make time for you today.",
    "I want to be the reason you smile before falling asleep.",
    "I'd love to walk beside you with my hand in yours.",
    "I think I'd feel very lucky falling asleep in your arms.",
    "I want to make memories with you, not just messages.",
    "Would you let me take you on a date this weekend?",
    "I'd love to take you out for coffee.",
    "Are you free this Friday? I'd like to see you.",
    "Want to go for a walk with me sometime?",
    "Can I take you out for dinner?",
    "I'd love to show you my favourite café.",
    "Would you join me for a movie date?",
    "How about we continue this conversation over coffee?",
    "I'd really like to spend some time with you, just us.",
    "Can I take you out and see where things go?",
    "Want to get dessert together this weekend?",
    "Would you let me plan a little date for us?",
    "Let's get coffee and see if we click in person.",
    "I'd like to see you outside our usual routine.",
    "Want to go out with me? I promise good conversation.",
    "I'd love to take you somewhere with a beautiful view.",
    "Are you available Saturday? I'd like to make you dinner.",
    "Let's go somewhere we can talk for hours.",
    "I'd like to take you somewhere nice.",
    "Would you say yes to a date with me?",
    "I have been wanting to ask you out. Is now a good time?",
    "Let's make a plan to see each other soon.",
    "Can I take you out for your favourite food?",
    "Let's turn this flirting into an actual date.",
    "I think we'd have a lovely time together. Want to find out?",
    "My friends are tired of hearing me mention you.",
    "I blame you for this silly grin on my face.",
    "I had a clever reply, but your smile distracted me.",
    "You make butterflies feel like a full-time job.",
    "I'm trying to act mysterious, but I just want to talk to you.",
    "If I keep flirting, will you flirt back?",
    "I think we're one good conversation away from a date.",
    "You have no business being this adorable in my notifications.",
    "I'm not saying I have a crush, but you're making a strong case.",
    "You should stop being so likeable; it's inconvenient for my heart.",
    "I would pretend not to care, but I clearly do.",
    "You're making me reconsider my plan to stay single.",
    "I like your humour, your smile, and the way you talk to me.",
    "You keep giving me reasons to like you more.",
    "You are becoming a very sweet problem.",
    "I think we flirt a little too well for this to be accidental.",
    "You make my heart do something very inconvenient.",
    "I think I deserve a date after all this flirting.",
    "I wonder how long we can pretend we don't like each other.",
    "I want to be a little more obvious about my feelings.",
    "I like your confidence, especially when you're flirting with me.",
    "I have a soft spot for you, and it's getting bigger.",
    "You make me want to be honest about how attractive I find you.",
    "You're the kind of distraction I don't want to fix.",
    "I like you, and I'd love to take you out if you're interested."
]

In [5]:
flirt_df=pd.DataFrame({"message":flirty_messages,"label":1})

In [6]:
flirt_df

                                               message  label
0                        You looked really cute today.      1
1                   That smile of yours is dangerous 😍      1
2        How do you manage to look so good every time?      1
3           I have to admit, you're pretty attractive.      1
4                      Your voice is honestly so nice.      1
..                                                 ...    ...
245  I like your confidence, especially when you're...      1
246  I have a soft spot for you, and it's getting b...      1
247  You make me want to be honest about how attrac...      1
248  You're the kind of distraction I don't want to...      1
249  I like you, and I'd love to take you out if yo...      1

[250 rows x 2 columns]

In [69]:
## Taking non-flirty messages from whatsapp chat

In [7]:
## Loading whatsapp text
import pandas as pd
df=pd.read_csv("mabel.txt",header=None,on_bad_lines='skip',encoding='utf8')
df=df.drop(0)
df.columns=["Date","Chat"]
message=df["Chat"].str.split("-",n=1,expand=True)
df["Time"]=message[0]
message1=message[1].str.split(":",n=1,expand=True)
df["Name"]=message1[0]
df["Chat"]=message1[1]
df=df[["Date","Time","Name","Chat"]]
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

In [70]:
# Merging both flirty and non-flirty conversations into single dataframe

In [8]:
non_flirty_df=pd.DataFrame({"message":df["Chat"],
                            "label":0})
#concatenate both df
df_final=pd.concat([flirt_df,non_flirty_df],ignore_index=True)

print(df_final.shape)
print(df_final["label"].value_counts())

(300, 2)
label
1    250
0     50
Name: count, dtype: int64

In [71]:
# As we have only few non-flirty messages, adding more manual non-flirty messages

In [10]:
non_flirty_messages = [
    "Good morning.",
    "Good night.",
    "How are you?",
    "I'm fine, thank you.",
    "What are you doing?",
    "Where are you now?",
    "Did you reach home?",
    "Have you had lunch?",
    "Have you had breakfast?",
    "Have you had dinner?",
    "What time is it?",
    "Are you busy right now?",
    "Can I call you?",
    "I'll call you later.",
    "Please call me when you're free.",
    "I missed your call.",
    "Sorry, I couldn't answer.",
    "My phone was on silent.",
    "I was in a meeting.",
    "I'll message you later.",
    "Did you see my message?",
    "Please check WhatsApp.",
    "Send me the details.",
    "Can you share the file?",
    "I have sent the document.",
    "Please check your email.",
    "Did you receive the email?",
    "I'll send it tomorrow.",
    "Please confirm once you receive it.",
    "Thank you for your help.",
    "You're welcome.",
    "No problem.",
    "That's fine.",
    "Okay, noted.",
    "Sure, I'll do it.",
    "I'll take care of it.",
    "Please let me know.",
    "Keep me updated.",
    "I'll get back to you.",
    "Let me check and confirm.",
    "What is the update?",
    "Any progress on this?",
    "Is the task completed?",
    "I have completed the task.",
    "The work is still in progress.",
    "I need some more time.",
    "I'll finish it by evening.",
    "Please review the report.",
    "There is an issue with the file.",
    "The system is not working.",
    "I can't log in.",
    "Please reset the password.",
    "The application is loading slowly.",
    "I have raised a ticket.",
    "The issue has been resolved.",
    "Please try again.",
    "Can you share the screenshot?",
    "I have attached the screenshot.",
    "Please check the error message.",
    "The data is not matching.",
    "We need to validate the results.",
    "The test case has failed.",
    "All test cases passed.",
    "Please update the status.",
    "The meeting starts at ten.",
    "The meeting has been postponed.",
    "Are you joining the meeting?",
    "Please join the call.",
    "I'll be five minutes late.",
    "The meeting is over.",
    "I'll share the minutes.",
    "Please check your calendar.",
    "What time works for you?",
    "Let's discuss this tomorrow.",
    "We can talk after lunch.",
    "I'll be available after three.",
    "Please send the meeting link.",
    "The link is not opening.",
    "Can you resend the link?",
    "I have booked the meeting room.",
    "The client has joined the call.",
    "We need to inform the manager.",
    "I'll check with the team.",
    "Please coordinate with the team.",
    "The deadline is Friday.",
    "We need to finish this today.",
    "The client requested some changes.",
    "I'll update the document.",
    "Please use the latest version.",
    "The old file is outdated.",
    "I have uploaded the report.",
    "Please download the attachment.",
    "The server is down.",
    "The network is unstable.",
    "My internet connection is slow.",
    "Can you hear me clearly?",
    "Your voice is breaking.",
    "The call got disconnected.",
    "I'll reconnect in a minute.",
    "Please mute your microphone.",
    "The presentation is ready.",
    "I need the final numbers.",
    "Can you verify the figures?",
    "The report looks correct.",
    "There are a few changes needed.",
    "Please correct the spelling.",
    "I have shared the revised version.",
    "The file size is too large.",
    "Can you send it as a PDF?",
    "Please print two copies.",
    "I'll bring the documents.",
    "Where should I submit this?",
    "The form is incomplete.",
    "Please fill in the missing details.",
    "I have submitted the form.",
    "The approval is pending.",
    "We received the confirmation.",
    "Please follow up with them.",
    "I'll send a reminder.",
    "The payment has been processed.",
    "The amount is incorrect.",
    "Please check the invoice.",
    "I have paid the bill.",
    "The receipt is attached.",
    "When is the last date?",
    "The deadline has been extended.",
    "Please keep a copy for reference.",
    "I'll save it in the folder.",
    "Which folder should I use?",
    "The folder is empty.",
    "I can't find the document.",
    "Please share the file path.",
    "The link has expired.",
    "I need access to the folder.",
    "Please grant permission.",
    "I have updated the spreadsheet.",
    "The formula is not working.",
    "There is a duplicate entry.",
    "Please remove the extra row.",
    "The data needs cleaning.",
    "I'll check the database.",
    "The query is running.",
    "The output looks correct.",
    "We need to check the missing values.",
    "Please run the script again.",
    "The code has an error.",
    "I fixed the bug.",
    "The program is running now.",
    "Please share the notebook.",
    "I have pushed the changes.",
    "The build was successful.",
    "The deployment is complete.",
    "We need to test it once more.",
    "Please check the logs.",
    "The issue happens intermittently.",
    "I'll investigate the problem.",
    "Can you reproduce the error?",
    "The steps are mentioned in the document.",
    "Please follow the instructions.",
    "I have completed the review.",
    "The feedback has been shared.",
    "Please make the requested changes.",
    "I'll update you after testing.",
    "We can close the ticket.",
    "The ticket is still open.",
    "Please assign it to the right person.",
    "The team is working on it.",
    "I need clarification on one point.",
    "Could you explain this requirement?",
    "I have a question about the task.",
    "Please provide an example.",
    "That answers my question.",
    "I understand now.",
    "Let me verify that.",
    "I agree with the approach.",
    "We should discuss the alternatives.",
    "This solution should work.",
    "Let's keep the current approach.",
    "We can revisit this later.",
    "I'll prepare the summary.",
    "Please share the agenda.",
    "The session starts at two.",
    "The training is scheduled for Monday.",
    "Have you completed the assignment?",
    "I finished the exercise.",
    "The instructor shared the notes.",
    "Please check the course portal.",
    "The video is available now.",
    "I need help with this topic.",
    "Can you explain the next step?",
    "I'll practise this example.",
    "The output differs from the expected result.",
    "Please check the instructions again.",
    "I have saved the changes.",
    "The file is ready for review.",
    "I'll send the final version shortly.",
    "Thanks for letting me know.",
    "Noted, I'll follow up tomorrow.",
    "I'll be offline for a while.",
    "I'm travelling to the office.",
    "Traffic is heavy today.",
    "The bus is delayed.",
    "I'll reach by ten thirty.",
    "I'm on the way.",
    "Please wait near the entrance.",
    "I'll meet you at the reception.",
    "The location has changed.",
    "Please share the address.",
    "I'll be working from home today.",
    "I'm taking leave tomorrow.",
    "I have an appointment this afternoon.",
    "I'll return after the break.",
    "Please inform the others.",
    "The schedule has been updated.",
    "Let's reschedule the discussion.",
    "Tomorrow works for me.",
    "Today won't be possible.",
    "I'll confirm the date later."
]

In [11]:
non_flirty_df1=pd.DataFrame({"message":non_flirty_messages, "label":0})

In [72]:
# Merging the newly added messages with the previously available messages into a single dataframe

In [12]:
#concatenate both df
df_final=pd.concat([df_final,non_flirty_df1],ignore_index=True)
print(df_final.shape)
print(df_final["label"].value_counts())

(518, 2)
label
0    268
1    250
Name: count, dtype: int64

In [13]:
# checking for missing values, duplicates 
import pandas as pd

print(df_final.shape)
print(df_final.columns.tolist())
print(df_final.isnull().sum())

# Remove rows with missing text or labels
df_final = df_final.dropna(subset=["message", "label"]).copy()

# Standardize message whitespace
df_final["message"] = (
    df_final["message"]
    .astype(str)
    .str.strip()
)

df_final = df_final[df_final["message"] != ""]

# Check duplicate messages
print("Duplicate messages:", df_final["message"].duplicated().sum())

(518, 2)
['message', 'label']
message    0
label      0
dtype: int64
Duplicate messages: 1

In [14]:
# Keep the first message and delete the other duplicate
df_final = df_final.drop_duplicates(
    subset=["message"],
    keep="first"
).reset_index(drop=True)

In [15]:
df_final["label"].value_counts()

label
0    267
1    250
Name: count, dtype: int64

In [16]:
# split the data into training and test data
from sklearn.model_selection import train_test_split
X=df_final["message"]
Y=df_final["label"].astype(int)
X_train,X_test,Y_train,Y_test=train_test_split(X, Y, test_size=0.20, random_state=42, stratify=Y)
print("Training samples:", len(X_train))
print("Testing samples", len(X_test))
print("Training level distribution:")
print(Y_train.value_counts())

Training samples: 413
Testing samples 104
Training level distribution:
label
0    213
1    200
Name: count, dtype: int64

In [73]:
# Compare the performance of different models on the created dataframe and displaying the results

In [18]:

import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB, ComplementNB
from sklearn.svm import LinearSVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# 1. Define the classification models
models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        class_weight="balanced",
        random_state=42
    ),
    "Multinomial NB": MultinomialNB(),
    "Complement NB": ComplementNB(),
    "Linear SVM": LinearSVC(
        class_weight="balanced",
        random_state=42,
        max_iter=5000
    )
}

# 2. Train models and collect evaluation results
trained_models = {}
results = []

for name, classifier in models.items():

    # Create TF-IDF + classifier pipeline
    pipeline = Pipeline([
        ("tfidf", TfidfVectorizer(
            ngram_range=(1, 2),
            sublinear_tf=True
        )),
        ("classifier", classifier)
    ])

    # Train the model
    pipeline.fit(X_train, Y_train)

    # Predict test labels
    y_pred = pipeline.predict(X_test)

    # Save the trained pipeline
    trained_models[name] = pipeline

    # Generate label-wise classification metrics
    report = classification_report(
        Y_test,
        y_pred,
        labels=[0, 1],
        target_names=["Non-flirty", "Flirty"],
        output_dict=True,
        zero_division=0
    )

    # Store overall and label-wise metrics
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(Y_test, y_pred),

        "Non-flirty Precision":
            report["Non-flirty"]["precision"],
        "Non-flirty Recall":
            report["Non-flirty"]["recall"],
        "Non-flirty F1":
            report["Non-flirty"]["f1-score"],

        "Flirty Precision":
            report["Flirty"]["precision"],
        "Flirty Recall":
            report["Flirty"]["recall"],
        "Flirty F1":
            report["Flirty"]["f1-score"],

        "Macro F1": report["macro avg"]["f1-score"],
        "Weighted F1": report["weighted avg"]["f1-score"]
    })

# 3. Display the model comparison table
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="Flirty F1",
    ascending=False
).reset_index(drop=True)

print("=" * 100)
print("MODEL COMPARISON")
print("=" * 100)
print(results_df.round(3).to_string(index=False))

# 4. Display detailed classification reports and confusion matrices
for name, pipeline in trained_models.items():

    y_pred = pipeline.predict(X_test)

    print("\n" + "=" * 60)
    print(f"MODEL: {name}")
    print("=" * 60)

    print("\nClassification Report:")
    print(classification_report(
        Y_test,
        y_pred,
        labels=[0, 1],
        target_names=["Non-flirty", "Flirty"],
        digits=3,
        zero_division=0
    ))

    print("Confusion Matrix:")
    print(confusion_matrix(Y_test, y_pred, labels=[0, 1]))

====================================================================================================
MODEL COMPARISON
====================================================================================================
              Model  Accuracy  Non-flirty Precision  Non-flirty Recall  Non-flirty F1  Flirty Precision  Flirty Recall  Flirty F1  Macro F1  Weighted F1
         Linear SVM     0.962                   1.0              0.926          0.962             0.926            1.0      0.962     0.962        0.962
     Multinomial NB     0.923                   1.0              0.852          0.920             0.862            1.0      0.926     0.923        0.923
      Complement NB     0.923                   1.0              0.852          0.920             0.862            1.0      0.926     0.923        0.923
Logistic Regression     0.904                   1.0              0.815          0.898             0.833            1.0      0.909     0.904        0.903

============================================================
MODEL: Logistic Regression
============================================================

Classification Report:
              precision    recall  f1-score   support

  Non-flirty      1.000     0.815     0.898        54
      Flirty      0.833     1.000     0.909        50

    accuracy                          0.904       104
   macro avg      0.917     0.907     0.904       104
weighted avg      0.920     0.904     0.903       104

Confusion Matrix:
[[44 10]
 [ 0 50]]

============================================================
MODEL: Multinomial NB
============================================================

Classification Report:
              precision    recall  f1-score   support

  Non-flirty      1.000     0.852     0.920        54
      Flirty      0.862     1.000     0.926        50

    accuracy                          0.923       104
   macro avg      0.931     0.926     0.923       104
weighted avg      0.934     0.923     0.923       104

Confusion Matrix:
[[46  8]
 [ 0 50]]

============================================================
MODEL: Complement NB
============================================================

Classification Report:
              precision    recall  f1-score   support

  Non-flirty      1.000     0.852     0.920        54
      Flirty      0.862     1.000     0.926        50

    accuracy                          0.923       104
   macro avg      0.931     0.926     0.923       104
weighted avg      0.934     0.923     0.923       104

Confusion Matrix:
[[46  8]
 [ 0 50]]

============================================================
MODEL: Linear SVM
============================================================

Classification Report:
              precision    recall  f1-score   support

  Non-flirty      1.000     0.926     0.962        54
      Flirty      0.926     1.000     0.962        50

    accuracy                          0.962       104
   macro avg      0.963     0.963     0.962       104
weighted avg      0.964     0.962     0.962       104

Confusion Matrix:
[[50  4]
 [ 0 50]]

In [74]:
# As per the above comparison Linear SVM is the best_model

In [19]:
best_model = trained_models["Linear SVM"]

print("Best model selected: Linear SVM")

Best model selected: Linear SVM

In [20]:
# Apply the best model SVM to the realtime whatsapp chat
import pandas as pd
df1=pd.read_csv("Sugu.txt",header=None,on_bad_lines='skip',encoding='utf8')
df1=df1.drop(0)
df1
df1 = df1[[0, 1]].copy()
df1.columns = ["Date", "Chat"]
message=df1["Chat"].str.split("-",n=1,expand=True)
df1["Time"]=message[0]
message1=message[1].str.split(":",n=1,expand=True)
df1["Name"]=message1[0]
df1["Chat"]=message1[1]
df=df1[["Date","Time","Name","Chat"]]
df1

,Date,Chat,Time,Name
1,10/4/20,Is that yoga class good Femi,9:40 PM,Suganya tn
2,10/4/20,Preksha from jeeva parivardhanam yoga only u ...,11:18 PM,Suganya tn
3,10/5/20,89044 91142,5:31 AM,hameedfemina
4,10/5/20,This person name is Shashank,5:32 AM,hameedfemina
5,10/5/20,He s also one of the organizer,5:32 AM,hameedfemina
...,...,...,...,...
292,8/28/23,Ennaku project work la etha pakka mudiyathu.,12:39 PM,hameedfemina
293,8/28/23,Atha. Yarachum iruntha daily one hr etha path...,12:39 PM,hameedfemina
294,8/28/23,Ok maa will ask my friend if she says ok will...,12:39 PM,Suganya tn
295,8/28/23,Ellame requirement edukathan,12:39 PM,hameedfemina
296,8/28/23,Ok da,12:42 PM,Suganya tn

In [77]:
# Check the dataframe
print(df1.shape)

(296, 4)

In [83]:
print(df1.info())
print(df1.head())
print(df1.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296 entries, 1 to 296
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    296 non-null    object
 1   Chat    244 non-null    object
 2   Time    252 non-null    object
 3   Name    244 non-null    object
dtypes: object(4)
memory usage: 9.4+ KB
None
      Date                                               Chat        Time  \
1  10/4/20                       Is that yoga class good Femi    9:40 PM
2  10/4/20   Preksha from jeeva parivardhanam yoga only u ...   11:18 PM
3  10/5/20                                        89044 91142    5:31 AM
4  10/5/20                       This person name is Shashank    5:32 AM
5  10/5/20                     He s also one of the organizer    5:32 AM

            Name
1     Suganya tn
2     Suganya tn
3   hameedfemina
4   hameedfemina
5   hameedfemina
Date     0
Chat    52
Time    44
Name    52
dtype: int64

In [75]:
# Here the lengthy messages got displayed in date column

In [21]:
print(df1.shape)
display(df1.head(10))
display(df1[df1["Chat"].isna()].head(10))

(296, 4)

,Date,Chat,Time,Name
1,10/4/20,Is that yoga class good Femi,9:40 PM,Suganya tn
2,10/4/20,Preksha from jeeva parivardhanam yoga only u ...,11:18 PM,Suganya tn
3,10/5/20,89044 91142,5:31 AM,hameedfemina
4,10/5/20,This person name is Shashank,5:32 AM,hameedfemina
5,10/5/20,He s also one of the organizer,5:32 AM,hameedfemina
6,10/5/20,U can ping hin,5:32 AM,hameedfemina
7,10/5/20,Him,5:32 AM,hameedfemina
8,10/5/20,Join this this is useful,5:36 AM,hameedfemina
9,10/5/20,Only thing is need to wake up early. 1 week y...,5:37 AM,hameedfemina
10,10/7/20,Namaste 🙏,7:39 PM,hameedfemina

                                                 Date Chat Time Name
11     *Jeeva Parivarthan* is now conducting a *FREE*  NaN  NaN  NaN
12                           *Online Trataka Session*  NaN  NaN  NaN
13                                     *When- Sunday*  NaN  NaN  NaN
14                                    *Time- 6:30 PM*  NaN  NaN  NaN
15                           *DATE-11th October 2020*  NaN  NaN  NaN
16  If you are interested to join the Trataka sess...  NaN  NaN  NaN
17                               *JP TRATAKA SESSION*  NaN  NaN  NaN
18   https://chat.whatsapp.com/LGOhoZjJf1B2mHQwBlQfMF  NaN  NaN  NaN
19     ----------------------------------------------  NaN  NaN  NaN
20                                         *Trataka-*  NaN  NaN  NaN

In [80]:
df1.head(15)

,Date,Chat,Time,Name
1,10/4/20,Is that yoga class good Femi,9:40 PM,Suganya tn
2,10/4/20,Preksha from jeeva parivardhanam yoga only u ...,11:18 PM,Suganya tn
3,10/5/20,89044 91142,5:31 AM,hameedfemina
4,10/5/20,This person name is Shashank,5:32 AM,hameedfemina
5,10/5/20,He s also one of the organizer,5:32 AM,hameedfemina
6,10/5/20,U can ping hin,5:32 AM,hameedfemina
7,10/5/20,Him,5:32 AM,hameedfemina
8,10/5/20,Join this this is useful,5:36 AM,hameedfemina
9,10/5/20,Only thing is need to wake up early. 1 week y...,5:37 AM,hameedfemina
10,10/7/20,Namaste 🙏,7:39 PM,hameedfemina
11,*Jeeva Parivarthan* is now conducting a *FREE*,NaN,NaN,NaN
12,*Online Trataka Session*,NaN,NaN,NaN
13,*When- Sunday*,NaN,NaN,NaN
14,*Time- 6:30 PM*,NaN,NaN,NaN
15,*DATE-11th October 2020*,NaN,NaN,NaN

In [76]:
# Merging the continuation messages which are present in different columns into one and keeping it in the chat column

In [22]:
import pandas as pd

df1 = df1.copy()

# Identify rows that begin with a date like 10/4/20
is_message_start = pd.to_datetime(
    df1["Date"].astype(str),
    format="%m/%d/%y",
    errors="coerce"
).notna()

merged_rows = []

for _, row in df1.iterrows():
    if is_message_start.loc[row.name]:
        merged_rows.append({
            "Date": row["Date"],
            "Chat": str(row["Chat"]) if pd.notna(row["Chat"]) else "",
            "Time": row["Time"],
            "Name": row["Name"]
        })
    elif merged_rows:
        # Collect text from continuation-row columns in order
        parts = [
            str(row[col]).strip()
            for col in ["Date", "Chat", "Time", "Name"]
            if pd.notna(row[col])
            and str(row[col]).strip().lower() not in ["", "nan", "none"]
        ]

        if parts:
            merged_rows[-1]["Chat"] += "\n" + " ".join(parts)

df1 = pd.DataFrame(merged_rows)
df1 = df1.reset_index(drop=True)

display(df1.head(15))

,Date,Chat,Time,Name
0,10/4/20,Is that yoga class good Femi,9:40 PM,Suganya tn
1,10/4/20,Preksha from jeeva parivardhanam yoga only u ...,11:18 PM,Suganya tn
2,10/5/20,89044 91142,5:31 AM,hameedfemina
3,10/5/20,This person name is Shashank,5:32 AM,hameedfemina
4,10/5/20,He s also one of the organizer,5:32 AM,hameedfemina
5,10/5/20,U can ping hin,5:32 AM,hameedfemina
6,10/5/20,Him,5:32 AM,hameedfemina
7,10/5/20,Join this this is useful,5:36 AM,hameedfemina
8,10/5/20,Only thing is need to wake up early. 1 week y...,5:37 AM,hameedfemina
9,10/7/20,Namaste 🙏\n*Jeeva Parivarthan* is now conduct...,7:39 PM,hameedfemina
10,10/8/20,It is very good for eye,5:39 AM,hameedfemina
11,10/8/20,Kids can also follow this,5:39 AM,hameedfemina
12,10/8/20,Ok ma thanks sure,8:11 AM,Suganya tn
13,10/17/20,Sugu,12:35 PM,hameedfemina
14,10/17/20,I got slight pain from thought to till chess ...,12:36 PM,hameedfemina

In [23]:
df1["Chat"].isna().sum()

np.int64(0)

In [24]:
df1.isnull().sum()

Date    0
Chat    0
Time    0
Name    0
dtype: int64

In [25]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    244 non-null    object
 1   Chat    244 non-null    object
 2   Time    244 non-null    object
 3   Name    244 non-null    object
dtypes: object(4)
memory usage: 7.8+ KB

In [26]:
df_chat = df1[["Chat"]].copy()

display(df_chat.head())
print(df_chat.shape)

                                                Chat
0                       Is that yoga class good Femi
1   Preksha from jeeva parivardhanam yoga only u ...
2                                        89044 91142
3                       This person name is Shashank
4                     He s also one of the organizer

(244, 1)

In [27]:
# Predict labels for WhatsApp messages
df_chat["Predicted_Label"] = best_model.predict(
    df_chat["Chat"].fillna("").astype(str)
)

# Convert numeric labels to readable categories
df_chat["Prediction"] = df_chat["Predicted_Label"].map({
    0: "Non-flirty",
    1: "Flirty"
})

display(df_chat.head(10))

,Chat,Predicted_Label,Prediction
0,Is that yoga class good Femi,0,Non-flirty
1,Preksha from jeeva parivardhanam yoga only u ...,0,Non-flirty
2,89044 91142,0,Non-flirty
3,This person name is Shashank,0,Non-flirty
4,He s also one of the organizer,0,Non-flirty
5,U can ping hin,0,Non-flirty
6,Him,0,Non-flirty
7,Join this this is useful,0,Non-flirty
8,Only thing is need to wake up early. 1 week y...,0,Non-flirty
9,Namaste 🙏\n*Jeeva Parivarthan* is now conduct...,1,Flirty

In [28]:
flirty_messages=df_chat[df_chat["Predicted_Label"]==1]

In [29]:
flirty_messages

,Chat,Predicted_Label,Prediction
9,Namaste 🙏\n*Jeeva Parivarthan* is now conduct...,1,Flirty
14,I got slight pain from thought to till chess ...,1,Flirty
22,BP and all normal,1,Flirty
23,They asked me to take echo. I took that. With...,1,Flirty
25,Hey!\nI have taken part in this Event called ...,1,Flirty
26,This s my son do like him,1,Flirty
32,Due to stress only all these happened,1,Flirty
33,Like that they told,1,Flirty
34,They gave medicine for that but looks like sl...,1,Flirty
46,How r u,1,Flirty
56,One of my colleagues dad infected with corana...,1,Flirty
57,Better for him to get admittted in hospital femi,1,Flirty
61,But not got bed,1,Flirty
73,U know one of my relative husband passed away...,1,Flirty
74,3 days fever 3 rd day died with breathing tro...,1,Flirty
75,One of my colleague passed Femi. He have one ...,1,Flirty
81,That too he was in Netherland just came for h...,1,Flirty
85,God should save all Sugu. Kastama iruku. Unab...,1,Flirty
95,How r u sugu,1,Flirty
103,How r u ?,1,Flirty
104,How s health,1,Flirty
106,How r u,1,Flirty
109,U may feel fever or body pain don't worry,1,Flirty
111,Don't take any pain killer. Other than parave...,1,Flirty
115,For my husband.no body pain,1,Flirty
120,When we got Covid for him it came very minimal,1,Flirty
123,U take car of ur health augu,1,Flirty
130,Not able to do work,1,Flirty
132,Would like to speak to you when u free,1,Flirty
136,How r u,1,Flirty
138,How r u,1,Flirty
142,How s ur health,1,Flirty
146,This is one of my previous colleagues relative,1,Flirty
147,He lost job in vts,1,Flirty
150,He s looking for job,1,Flirty
151,In case if you can refer in Accenture,1,Flirty
155,One more my maid sister son also he s from fu...,1,Flirty
164,This guy lost job in cts,1,Flirty
172,Due to lay off,1,Flirty
176,This is my brother in law profile. He is look...,1,Flirty
180,Sugu for my experience how much sal I should ...,1,Flirty
182,You should get more than 25 lac,1,Flirty
185,If I jump I will get more,1,Flirty
186,Most of our junior who shift more compnay get...,1,Flirty
188,I m doing machine learning course so after co...,1,Flirty
209,https://halwakadai.com/content/4-about-us,1,Flirty
214,Sugu if possible refer him in Accenture site,1,Flirty
215,Sugu regarding tea shop I enquired and met fr...,1,Flirty
230,Sugu when u get time can u come up with compl...,1,Flirty
232,Sugu nambikayana yarachum irukanga laptop oda...,1,Flirty
233,What kind of job ma,1,Flirty
234,Will check and let you know,1,Flirty
237,Ennoda team ippo under training . Using one N...,1,Flirty
238,If we get good project and able to do it with...,1,Flirty

In [30]:
df_chat["Prediction"].value_counts()

Prediction
Non-flirty    190
Flirty         54
Name: count, dtype: int64

In [31]:
df_chat["SVM_Score"] = best_model.decision_function(
    df_chat["Chat"].fillna("").astype(str)
)

display(
    df_chat[df_chat["Predicted_Label"] == 1]
    [["Chat", "SVM_Score"]]
    .sort_values("SVM_Score")
    .head(15)
)

                                                  Chat  SVM_Score
214       Sugu if possible refer him in Accenture site   0.001060
209          https://halwakadai.com/content/4-about-us   0.004836
61                                     But not got bed   0.009557
232   Sugu nambikayana yarachum irukanga laptop oda...   0.014390
146     This is one of my previous colleagues relative   0.044975
9     Namaste 🙏\n*Jeeva Parivarthan* is now conduct...   0.047950
130                                Not able to do work   0.051571
75    One of my colleague passed Femi. He have one ...   0.077553
111   Don't take any pain killer. Other than parave...   0.092276
115                        For my husband.no body pain   0.112684
147                                 He lost job in vts   0.115573
176   This is my brother in law profile. He is look...   0.135738
188   I m doing machine learning course so after co...   0.136093
234                        Will check and let you know   0.142072
164                           This guy lost job in cts   0.150762

In [77]:
# As 54 non-flirty messages are marked as flirty,setting a threshold value to fine tune the model performance

In [32]:
threshold = 0.2

df_chat["Adjusted_Label"] = (
    df_chat["SVM_Score"] >= threshold
).astype(int)

df_chat["Adjusted_Prediction"] = df_chat["Adjusted_Label"].map({
    0: "Non-flirty",
    1: "Flirty"
})

print(df_chat["Adjusted_Prediction"].value_counts())

Adjusted_Prediction
Non-flirty    206
Flirty         38
Name: count, dtype: int64

In [78]:
# Still 38 non-flirty messages are marked as flirty

In [33]:
display(
    df_chat[df_chat["Adjusted_Label"] == 1]
    [["Chat", "SVM_Score"]]
    .sort_values("SVM_Score", ascending=False)
)

                                                  Chat  SVM_Score
132             Would like to speak to you when u free   1.459642
172                                     Due to lay off   1.425061
182                  You should get more than   25 lac   0.813314
26                           This s my son do like him   0.695473
57    Better for him to get admittted in hospital femi   0.649023
33                                 Like that they told   0.603013
73    U know one of my relative husband passed away...   0.596875
180   Sugu for my experience how much sal I should ...   0.522704
85    God should save all Sugu. Kastama iruku. Unab...   0.497111
186   Most of our junior who shift more compnay get...   0.473298
109          U may feel fever or body pain don't worry   0.453988
155   One more my maid sister son also he s from fu...   0.431660
34    They gave medicine for that but looks like sl...   0.428769
150                               He s looking for job   0.416113
151              In case if you can refer in Accenture   0.402070
238   If we get good project and able to do it with...   0.382167
123                       U take car of ur health augu   0.314457
74    3 days fever 3 rd day died with breathing tro...   0.309397
32               Due to stress only all these happened   0.308990
56    One of my colleagues dad infected with corana...   0.305755
22                                   BP and all normal   0.298035
14    I got slight pain from thought to till chess ...   0.290222
185                          If I jump I will get more   0.284344
23    They asked me to take echo. I took that. With...   0.279129
230   Sugu when u get time can u come up with compl...   0.260671
233                                What kind of job ma   0.233755
138                                            How r u   0.219936
95                                        How r u sugu   0.219936
46                                             How r u   0.219936
104                                       How s health   0.219936
142                                    How s ur health   0.219936
136                                            How r u   0.219936
103                                          How r u ?   0.219936
106                                            How r u   0.219936
215   Sugu regarding tea shop I enquired and met fr...   0.212912
81    That too he was in Netherland just came for h...   0.205868
120     When we got Covid for him it came very minimal   0.204542
25    Hey!\nI have taken part in this Event called ...   0.200602

In [34]:
review_df = df_chat[df_chat["Adjusted_Label"] == 1][
    ["Chat", "SVM_Score"]
].copy()

review_df["Actual_Label"] = "0"  # Enter 1 = flirty, 0 = non-flirty
review_df["Reason"] = "Ordinary conversation"

display(review_df)

,Chat,SVM_Score,Actual_Label,Reason
14,I got slight pain from thought to till chess ...,0.290222,0,Ordinary conversation
22,BP and all normal,0.298035,0,Ordinary conversation
23,They asked me to take echo. I took that. With...,0.279129,0,Ordinary conversation
25,Hey!\nI have taken part in this Event called ...,0.200602,0,Ordinary conversation
26,This s my son do like him,0.695473,0,Ordinary conversation
32,Due to stress only all these happened,0.308990,0,Ordinary conversation
33,Like that they told,0.603013,0,Ordinary conversation
34,They gave medicine for that but looks like sl...,0.428769,0,Ordinary conversation
46,How r u,0.219936,0,Ordinary conversation
56,One of my colleagues dad infected with corana...,0.305755,0,Ordinary conversation
57,Better for him to get admittted in hospital femi,0.649023,0,Ordinary conversation
73,U know one of my relative husband passed away...,0.596875,0,Ordinary conversation
74,3 days fever 3 rd day died with breathing tro...,0.309397,0,Ordinary conversation
81,That too he was in Netherland just came for h...,0.205868,0,Ordinary conversation
85,God should save all Sugu. Kastama iruku. Unab...,0.497111,0,Ordinary conversation
95,How r u sugu,0.219936,0,Ordinary conversation
103,How r u ?,0.219936,0,Ordinary conversation
104,How s health,0.219936,0,Ordinary conversation
106,How r u,0.219936,0,Ordinary conversation
109,U may feel fever or body pain don't worry,0.453988,0,Ordinary conversation
120,When we got Covid for him it came very minimal,0.204542,0,Ordinary conversation
123,U take car of ur health augu,0.314457,0,Ordinary conversation
132,Would like to speak to you when u free,1.459642,0,Ordinary conversation
136,How r u,0.219936,0,Ordinary conversation
138,How r u,0.219936,0,Ordinary conversation
142,How s ur health,0.219936,0,Ordinary conversation
150,He s looking for job,0.416113,0,Ordinary conversation
151,In case if you can refer in Accenture,0.402070,0,Ordinary conversation
155,One more my maid sister son also he s from fu...,0.431660,0,Ordinary conversation
172,Due to lay off,1.425061,0,Ordinary conversation
180,Sugu for my experience how much sal I should ...,0.522704,0,Ordinary conversation
182,You should get more than 25 lac,0.813314,0,Ordinary conversation
185,If I jump I will get more,0.284344,0,Ordinary conversation
186,Most of our junior who shift more compnay get...,0.473298,0,Ordinary conversation
215,Sugu regarding tea shop I enquired and met fr...,0.212912,0,Ordinary conversation
230,Sugu when u get time can u come up with compl...,0.260671,0,Ordinary conversation
233,What kind of job ma,0.233755,0,Ordinary conversation
238,If we get good project and able to do it with...,0.382167,0,Ordinary conversation

In [79]:
# Checking the non-flirty samples which marked as non-flirty
non_flirty_sample = df_chat[
    df_chat["Adjusted_Label"] == 0
].sample(
    n=min(20, (df_chat["Adjusted_Label"] == 0).sum()),
    random_state=42
)

display(non_flirty_sample[["Chat", "SVM_Score"]])

                                                  Chat  SVM_Score
16    Eve 5 clk only doctor will be back to check t...  -0.587765
9     Namaste 🙏\n*Jeeva Parivarthan* is now conduct...   0.047950
239       Ennaku project work la etha pakka mudiyathu.  -0.549788
98                                                  Kk  -0.216333
82    She s also having one kid 6 yes old. She s in...  -0.625564
117                                                  ?  -0.188542
214       Sugu if possible refer him in Accenture site   0.001060
197                                  Happy pongal Sugu  -0.188542
178                          Sure ma tomorrpw will see  -0.502635
218                                    <Media omitted>  -0.188542
122                                              Oh kk  -0.216333
199                                          Thank you  -0.250827
78    We should be careful enough. Second wave is w...  -0.129833
210                        Alapatiyan karupatti coffee  -0.053278
88    Regarding my colleagues father she shared thi...  -0.294034
113                   For some they will not feel any🙏  -0.344377
19                            You deleted this message  -0.577298
188   I m doing machine learning course so after co...   0.136093
166                                                 Ma  -0.282026
200                                               Sugu  -0.188542

In [80]:
# Predicting the labels using set of flirty messages

In [36]:
import pandas as pd

flirty_test_df = pd.DataFrame({
    "Chat": [
        "I can't stop thinking about you.",
        "You look so beautiful today.",
        "Are you always this cute or is it just with me?",
        "I was smiling at my phone because of you.",
        "I wish you were here with me right now.",
        "You make my heart race every time we talk.",
        "If I say I miss you, will you come see me?",
        "Stop being so charming, I might fall for you.",
        "You are the reason I keep checking my phone.",
        "I think I am starting to like you more than I should.",
        "Your smile is my favourite thing.",
        "I was hoping you would text me first.",
        "You looked really attractive in that photo.",
        "I could talk to you all night.",
        "Admit it, you missed me.",
        "You have no idea how much you affect me.",
        "I wish this conversation could last forever.",
        "You make ordinary days feel special.",
        "If we were together right now, I'd never let you leave early.",
        "Tell me honestly, do you ever think about me?"
    ]
})

# All examples are intended to be flirty
flirty_test_df["Actual_Label"] = 1

display(flirty_test_df)

                                                 Chat  Actual_Label
0                    I can't stop thinking about you.             1
1                        You look so beautiful today.             1
2     Are you always this cute or is it just with me?             1
3           I was smiling at my phone because of you.             1
4             I wish you were here with me right now.             1
5          You make my heart race every time we talk.             1
6          If I say I miss you, will you come see me?             1
7       Stop being so charming, I might fall for you.             1
8        You are the reason I keep checking my phone.             1
9   I think I am starting to like you more than I ...             1
10                  Your smile is my favourite thing.             1
11              I was hoping you would text me first.             1
12        You looked really attractive in that photo.             1
13                     I could talk to you all night.             1
14                           Admit it, you missed me.             1
15           You have no idea how much you affect me.             1
16       I wish this conversation could last forever.             1
17               You make ordinary days feel special.             1
18  If we were together right now, I'd never let y...             1
19      Tell me honestly, do you ever think about me?             1

In [37]:
best_model = trained_models["Linear SVM"]

print("Best model selected: Linear SVM")

Best model selected: Linear SVM

In [38]:
# Predict using the original trained model
flirty_test_df["SVM_Score"] = best_model.decision_function(
    flirty_test_df["Chat"]
)

flirty_test_df["Model_Label"] = best_model.predict(
    flirty_test_df["Chat"]
)

flirty_test_df["Adjusted_Label"] = (
    flirty_test_df["SVM_Score"] >= 0.2
).astype(int)

flirty_test_df["Model_Prediction"] = (
    flirty_test_df["Adjusted_Label"].map({
        0: "Non-flirty",
        1: "Flirty"
    })
)

display(
    flirty_test_df[
        ["Chat", "SVM_Score", "Model_Prediction"]
    ].sort_values("SVM_Score", ascending=False)
)

,Chat,SVM_Score,Model_Prediction
9,I think I am starting to like you more than I ...,1.069115,Flirty
11,I was hoping you would text me first.,1.057122,Flirty
19,"Tell me honestly, do you ever think about me?",1.025592,Flirty
3,I was smiling at my phone because of you.,0.899981,Flirty
4,I wish you were here with me right now.,0.880843,Flirty
7,"Stop being so charming, I might fall for you.",0.860455,Flirty
15,You have no idea how much you affect me.,0.857513,Flirty
17,You make ordinary days feel special.,0.849887,Flirty
13,I could talk to you all night.,0.839498,Flirty
12,You looked really attractive in that photo.,0.826765,Flirty
5,You make my heart race every time we talk.,0.812406,Flirty
1,You look so beautiful today.,0.762358,Flirty
10,Your smile is my favourite thing.,0.761913,Flirty
6,"If I say I miss you, will you come see me?",0.694069,Flirty
2,Are you always this cute or is it just with me?,0.670371,Flirty
18,"If we were together right now, I'd never let y...",0.652204,Flirty
0,I can't stop thinking about you.,0.520216,Flirty
14,"Admit it, you missed me.",0.337712,Flirty
16,I wish this conversation could last forever.,0.291358,Flirty
8,You are the reason I keep checking my phone.,-0.015785,Non-flirty

In [81]:
# here one messages which is flirty are marked as Non-Flirty

In [82]:
# Predicting the label using another whatsapp conversation

In [56]:
import pandas as pd
df2=pd.read_csv("hf.txt",header=None,on_bad_lines='skip',encoding='utf8')
df2

,0,1,2,3
0,25/08/2023,9:17 pm - Messages and calls are end-to-end e...,not even WhatsApp,can read or listen to them. Tap to learn more.
1,25/08/2023,9:17 pm - Hope Artificial Intelligence: *Rece...,NaN,NaN
2,Hey Congrats!! 🎉 For the Great Decision you m...,NaN,NaN,NaN
3,To the next step,Use this below link to book a 1:1 call for *Cu...,NaN,NaN
4,📅 *Book a 1:1 Call-* https://calendly.com/hope...,NaN,NaN,NaN
...,...,...,...,...
95,30/08/2023,10:47 am - Hameed Femina Aug23: After that I ...,NaN,NaN
96,30/08/2023,10:47 am - Hameed Femina Aug23: After that we...,NaN,NaN
97,30/08/2023,10:49 am - Hope Artificial Intelligence: Ok mam,NaN,NaN
98,30/08/2023,1:10 pm - Hameed Femina Aug23: Hi shall we co...,NaN,NaN
99,30/08/2023,1:12 pm - Hope Artificial Intelligence: ok mam,NaN,NaN

In [57]:
df2.shape
df2.head(15)

,0,1,2,3
0,25/08/2023,9:17 pm - Messages and calls are end-to-end e...,not even WhatsApp,can read or listen to them. Tap to learn more.
1,25/08/2023,9:17 pm - Hope Artificial Intelligence: *Rece...,NaN,NaN
2,Hey Congrats!! 🎉 For the Great Decision you m...,NaN,NaN,NaN
3,To the next step,Use this below link to book a 1:1 call for *Cu...,NaN,NaN
4,📅 *Book a 1:1 Call-* https://calendly.com/hope...,NaN,NaN,NaN
5,*Note: If you already booked the 1:1 call,ignore this message. Please do not book again.*,NaN,NaN
6,Your Details:,NaN,NaN,NaN
7,📧 *Email-ID:* hameedfemina@gmail.com,NaN,NaN,NaN
8,📞 *Phone:*+919535768907,NaN,NaN,NaN
9,Best Regards,,NaN,NaN
10,Ramisha Rani K,NaN,NaN,NaN
11,25/08/2023,9:26 pm - Hope Artificial Intelligence: *Hame...,NaN,NaN
12,📆 Customised Career Path Call has been Booked.,NaN,NaN,NaN
13,📝 *Meeting Details*,NaN,NaN,NaN
14,*Scheduled Time:* 03:00pm - Saturday,August 26,2023,NaN

In [58]:
# Make a working copy to preserve the original dataframe
df_cleaning = df2.copy()

# Combine non-empty cells in each row
df_cleaning["Raw_Text"] = df_cleaning.apply(
    lambda row: " ".join(
        str(value).strip()
        for value in row
        if pd.notna(value) and str(value).strip()
    ),
    axis=1
)

display(df_cleaning[["Raw_Text"]].head(20))

                                             Raw_Text
0   25/08/2023 9:17 pm - Messages and calls are en...
1   25/08/2023 9:17 pm - Hope Artificial Intellige...
2   Hey Congrats!! 🎉 For the Great Decision you ma...
3   To the next step Use this below link to book a...
4   📅 *Book a 1:1 Call-* https://calendly.com/hope...
5   *Note: If you already booked the 1:1 call igno...
6                                       Your Details:
7                📧 *Email-ID:* hameedfemina@gmail.com
8                             📞 *Phone:*+919535768907
9                                        Best Regards
10                                     Ramisha Rani K
11  25/08/2023 9:26 pm - Hope Artificial Intellige...
12     📆 Customised Career Path Call has been Booked.
13                                📝 *Meeting Details*
14  *Scheduled Time:* 03:00pm - Saturday August 26...
15  ⏰ *Google Meet Link:* https://calendly.com/eve...
16                       🌍 *Time Zone:* Asia/Calcutta
17  🤝 Eagerly waiting to discuss with you about yo...
18                 *See you on the Scheduled Time !!*
19         *Note: Star this message for Meeting link*

In [60]:
import re
import pandas as pd

# Matches WhatsApp message starts like:
# 25/08/2023 9:17 pm - Sender: Message
message_start = re.compile(
    r"^\d{1,2}/\d{1,2}/\d{4}\s+"
    r"\d{1,2}:\d{2}\s*[apAP][mM]\s+-\s+"
)

messages = []
current_message = None

for text in df_cleaning["Raw_Text"].fillna("").astype(str):
    text = text.strip()

    if not text:
        continue

    if message_start.match(text):
        if current_message is not None:
            messages.append(current_message)

        current_message = text
    elif current_message is not None:
        # Append continuation lines to the current message
        current_message += " " + text
    else:
        # Keep track of text before the first detected message
        print("Text before first message:", text[:100])

if current_message is not None:
    messages.append(current_message)

df_parsed = pd.DataFrame({"Raw_Message": messages})

print("Parsed WhatsApp messages:", len(df_parsed))
display(df_parsed.head(20))

Parsed WhatsApp messages: 70

                                          Raw_Message
0   25/08/2023 9:17 pm - Messages and calls are en...
1   25/08/2023 9:17 pm - Hope Artificial Intellige...
2   25/08/2023 9:26 pm - Hope Artificial Intellige...
3        28/08/2023 3:38 pm - Hameed Femina Aug23: Hi
4   28/08/2023 4:05 pm - Hameed Femina Aug23: <Med...
5   28/08/2023 4:09 pm - Hameed Femina Aug23: I th...
6   28/08/2023 4:11 pm - Hameed Femina Aug23: Say ...
7   28/08/2023 4:11 pm - Hameed Femina Aug23: I m ...
8   28/08/2023 4:22 pm - Hope Artificial Intellige...
9   28/08/2023 4:22 pm - Hope Artificial Intellige...
10  28/08/2023 4:31 pm - Hameed Femina Aug23: <Med...
11  28/08/2023 4:36 pm - Hameed Femina Aug23: Hi w...
12        28/08/2023 4:36 pm - Hameed Femina Aug23: ?
13  28/08/2023 6:02 pm - Hope Artificial Intellige...
14  28/08/2023 6:02 pm - Hope Artificial Intellige...
15  28/08/2023 6:33 pm - Hameed Femina Aug23: <Med...
16  28/08/2023 6:34 pm - Hope Artificial Intellige...
17  28/08/2023 6:34 pm - Hope Artificial Intellige...
18  28/08/2023 6:37 pm - Hope Artificial Intellige...
19  28/08/2023 6:43 pm - Hameed Femina Aug23: I la...

In [61]:
import re
import pandas as pd

header_pattern = re.compile(
    r"^(?P<Date>\d{1,2}/\d{1,2}/\d{4})\s+"
    r"(?P<Time>\d{1,2}:\d{2}\s*[apAP][mM])\s+-\s+"
    r"(?P<Rest>.*)$"
)

def parse_message(raw_message):
    match = header_pattern.match(raw_message)

    if not match:
        return pd.Series({
            "Date": None,
            "Time": None,
            "Name": None,
            "Chat": raw_message
        })

    rest = match.group("Rest")

    # Split sender and message at the first colon
    if ": " in rest:
        name, chat = rest.split(": ", 1)
    else:
        name, chat = None, rest

    return pd.Series({
        "Date": match.group("Date"),
        "Time": match.group("Time"),
        "Name": name,
        "Chat": chat
    })

df_chat_new = pd.concat(
    [
        df_parsed["Raw_Message"],
        df_parsed["Raw_Message"].apply(parse_message)
    ],
    axis=1
)

display(df_chat_new.head(12))
print("Parsed rows:", len(df_chat_new))
print("Rows missing sender:", df_chat_new["Name"].isna().sum())

,Raw_Message,Date,Time,Name,Chat
0,25/08/2023 9:17 pm - Messages and calls are en...,25/08/2023,9:17 pm,None,Messages and calls are end-to-end encrypted. N...
1,25/08/2023 9:17 pm - Hope Artificial Intellige...,25/08/2023,9:17 pm,Hope Artificial Intelligence,*Received Your Initial Payment*. Hey Congrats!...
2,25/08/2023 9:26 pm - Hope Artificial Intellige...,25/08/2023,9:26 pm,Hope Artificial Intelligence,*Hameed Femina* *!! Successfully your slot has...
3,28/08/2023 3:38 pm - Hameed Femina Aug23: Hi,28/08/2023,3:38 pm,Hameed Femina Aug23,Hi
4,28/08/2023 4:05 pm - Hameed Femina Aug23: <Med...,28/08/2023,4:05 pm,Hameed Femina Aug23,<Media omitted>
5,28/08/2023 4:09 pm - Hameed Femina Aug23: I th...,28/08/2023,4:09 pm,Hameed Femina Aug23,I thought to a application. In that if user gi...
6,28/08/2023 4:11 pm - Hameed Femina Aug23: Say ...,28/08/2023,4:11 pm,Hameed Femina Aug23,Say I have taken Amazon 10 yr data till 25 th ...
7,28/08/2023 4:11 pm - Hameed Femina Aug23: I m ...,28/08/2023,4:11 pm,Hameed Femina Aug23,I m giving today's date or date within one mon...
8,28/08/2023 4:22 pm - Hope Artificial Intellige...,28/08/2023,4:22 pm,Hope Artificial Intelligence,<Media omitted>
9,28/08/2023 4:22 pm - Hope Artificial Intellige...,28/08/2023,4:22 pm,Hope Artificial Intelligence,<Media omitted>
10,28/08/2023 4:31 pm - Hameed Femina Aug23: <Med...,28/08/2023,4:31 pm,Hameed Femina Aug23,<Media omitted>
11,28/08/2023 4:36 pm - Hameed Femina Aug23: Hi w...,28/08/2023,4:36 pm,Hameed Femina Aug23,Hi will I get project assistant 1st for these ...

Parsed rows: 70
Rows missing sender: 1

In [62]:
# dropping the first row which is not a conversation
df_chat_analysis = df_chat_new.drop(index=0).reset_index(drop=True)

In [63]:
df_chat_analysis

,Raw_Message,Date,Time,Name,Chat
0,25/08/2023 9:17 pm - Hope Artificial Intellige...,25/08/2023,9:17 pm,Hope Artificial Intelligence,*Received Your Initial Payment*. Hey Congrats!...
1,25/08/2023 9:26 pm - Hope Artificial Intellige...,25/08/2023,9:26 pm,Hope Artificial Intelligence,*Hameed Femina* *!! Successfully your slot has...
2,28/08/2023 3:38 pm - Hameed Femina Aug23: Hi,28/08/2023,3:38 pm,Hameed Femina Aug23,Hi
3,28/08/2023 4:05 pm - Hameed Femina Aug23: <Med...,28/08/2023,4:05 pm,Hameed Femina Aug23,<Media omitted>
4,28/08/2023 4:09 pm - Hameed Femina Aug23: I th...,28/08/2023,4:09 pm,Hameed Femina Aug23,I thought to a application. In that if user gi...
...,...,...,...,...,...
64,30/08/2023 10:47 am - Hameed Femina Aug23: Aft...,30/08/2023,10:47 am,Hameed Femina Aug23,After that I will will that web development de...
65,30/08/2023 10:47 am - Hameed Femina Aug23: Aft...,30/08/2023,10:47 am,Hameed Femina Aug23,After that we can connect
66,30/08/2023 10:49 am - Hope Artificial Intellig...,30/08/2023,10:49 am,Hope Artificial Intelligence,Ok mam
67,30/08/2023 1:10 pm - Hameed Femina Aug23: Hi s...,30/08/2023,1:10 pm,Hameed Femina Aug23,Hi shall we connect by 2 pm?
68,30/08/2023 1:12 pm - Hope Artificial Intellige...,30/08/2023,1:12 pm,Hope Artificial Intelligence,ok mam

In [64]:
df_chat_analysis["Name"].value_counts()

Name
Hameed Femina Aug23             42
Hope Artificial Intelligence    27
Name: count, dtype: int64

In [65]:
df_chat_test = df_chat_analysis.copy()

df_chat_test["SVM_Score"] = best_model.decision_function(
    df_chat_test["Chat"].fillna("").astype(str)
)

df_chat_test["Predicted_Label"] = (
    df_chat_test["SVM_Score"] >= 0
).astype(int)

df_chat_test["Prediction"] = df_chat_test["Predicted_Label"].map({
    0: "Non-flirty",
    1: "Flirty"
})

print(df_chat_test["Prediction"].value_counts())

display(
    df_chat_test[
        ["Date", "Time", "Name", "Chat", "SVM_Score", "Prediction"]
    ]
)

Prediction
Non-flirty    58
Flirty        11
Name: count, dtype: int64

,Date,Time,Name,Chat,SVM_Score,Prediction
0,25/08/2023,9:17 pm,Hope Artificial Intelligence,*Received Your Initial Payment*. Hey Congrats!...,-0.838503,Non-flirty
1,25/08/2023,9:26 pm,Hope Artificial Intelligence,*Hameed Femina* *!! Successfully your slot has...,-0.597463,Non-flirty
2,28/08/2023,3:38 pm,Hameed Femina Aug23,Hi,-0.560904,Non-flirty
3,28/08/2023,4:05 pm,Hameed Femina Aug23,<Media omitted>,-0.188542,Non-flirty
4,28/08/2023,4:09 pm,Hameed Femina Aug23,I thought to a application. In that if user gi...,0.456190,Flirty
...,...,...,...,...,...,...
64,30/08/2023,10:47 am,Hameed Femina Aug23,After that I will will that web development de...,-0.614410,Non-flirty
65,30/08/2023,10:47 am,Hameed Femina Aug23,After that we can connect,-0.559439,Non-flirty
66,30/08/2023,10:49 am,Hope Artificial Intelligence,Ok mam,-1.079047,Non-flirty
67,30/08/2023,1:10 pm,Hameed Femina Aug23,Hi shall we connect by 2 pm?,-0.369699,Non-flirty
68,30/08/2023,1:12 pm,Hope Artificial Intelligence,ok mam,-1.079047,Non-flirty

In [66]:
flirty_messages = df_chat_test[
    df_chat_test["Predicted_Label"] == 1
].sort_values("SVM_Score", ascending=False)

display(
    flirty_messages[
        ["Date", "Time", "Name", "Chat", "SVM_Score"]
    ]
)

,Date,Time,Name,Chat,SVM_Score
23,28/08/2023,6:47 pm,Hope Artificial Intelligence,I gave access to you,0.614234
4,28/08/2023,4:09 pm,Hameed Femina Aug23,I thought to a application. In that if user gi...,0.456190
33,28/08/2023,7:19 pm,Hameed Femina Aug23,Unable to play,0.444547
27,28/08/2023,6:54 pm,Hameed Femina Aug23,Tamil one also unable to play,0.395842
62,30/08/2023,10:46 am,Hameed Femina Aug23,About to finish word cloud cloud,0.291748
37,29/08/2023,5:35 pm,Hameed Femina Aug23,Gave TSLA and tried,0.222684
63,30/08/2023,10:46 am,Hameed Femina Aug23,In my notebook,0.195329
28,28/08/2023,6:57 pm,Hameed Femina Aug23,Unable to play any video,0.115468
59,29/08/2023,8:52 pm,Hameed Femina Aug23,Thank you so much,0.037687
58,29/08/2023,8:52 pm,Hameed Femina Aug23,I have to recreate everything in my offic pc. ...,0.034531
17,28/08/2023,6:37 pm,Hope Artificial Intelligence,Kindly send your mail id after you signup,0.027454

In [68]:
flirty_review = flirty_messages[
    ["Date", "Time", "Name", "Chat", "SVM_Score"]
].copy()

flirty_review["Actual_Label"] = 0

display(flirty_review)

,Date,Time,Name,Chat,SVM_Score,Actual_Label
23,28/08/2023,6:47 pm,Hope Artificial Intelligence,I gave access to you,0.614234,0
4,28/08/2023,4:09 pm,Hameed Femina Aug23,I thought to a application. In that if user gi...,0.456190,0
33,28/08/2023,7:19 pm,Hameed Femina Aug23,Unable to play,0.444547,0
27,28/08/2023,6:54 pm,Hameed Femina Aug23,Tamil one also unable to play,0.395842,0
62,30/08/2023,10:46 am,Hameed Femina Aug23,About to finish word cloud cloud,0.291748,0
37,29/08/2023,5:35 pm,Hameed Femina Aug23,Gave TSLA and tried,0.222684,0
63,30/08/2023,10:46 am,Hameed Femina Aug23,In my notebook,0.195329,0
28,28/08/2023,6:57 pm,Hameed Femina Aug23,Unable to play any video,0.115468,0
59,29/08/2023,8:52 pm,Hameed Femina Aug23,Thank you so much,0.037687,0
58,29/08/2023,8:52 pm,Hameed Femina Aug23,I have to recreate everything in my offic pc. ...,0.034531,0
17,28/08/2023,6:37 pm,Hope Artificial Intelligence,Kindly send your mail id after you signup,0.027454,0

In [83]:
# Here even though all the messages are non-flirty , 11 out of 69 messages are marked as flirty