In [11]:
import pandas as pd

In [13]:
df=pd.read_csv("mabel.txt",header=None,on_bad_lines='skip',encoding='utf8')

In [15]:
df

           0                                                  1
0   05/12/19   1:42 pm - Messages to this chat and calls are...
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [17]:
df=df.drop(0)

In [19]:
df

           0                                                  1
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [21]:
# Below process is done to dataFrame with date, Name, Time, message
df.columns=["Date","Chat"]

In [23]:
df

        Date                                               Chat
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [25]:
message=df["Chat"].str.split("-",n=1,expand=True)

In [27]:
message

             0                                                  1
1     1:42 pm     Mabel Infoziant: Hi this is Mabel we just spoke
2     1:42 pm              Mabel Infoziant: What’s your full name
3     1:42 pm                                 AR❤: Ramisha Rani K
4     1:42 pm                                 Mabel Infoziant: Ok
5     1:42 pm             Mabel Infoziant: ramisharanik@gmail.com
6     1:43 pm                     Mabel Infoziant: Your email Id?
7     1:43 pm                                        AR❤: Yes Mam
8     1:43 pm    Mabel Infoziant: I will send 2 abstracts for ...
9     1:43 pm                                       AR❤: Yeah mam
10    1:43 pm    Mabel Infoziant: Give me the list that u have...
11    1:43 pm    Mabel Infoziant: Send me cbe office address a...
12    1:44 pm    AR❤: Yeah Mam within Evening I will forward y...
13    1:45 pm    AR❤: Tomorrow I have to visit the office.yet ...
14    1:48 pm                                 Mabel Infoziant: ok
15    1:48 pm    Mabel Infoziant: send the details of office l...
16    1:49 pm    AR❤: Sure mam. Soon I will share details with...
17    2:00 pm    AR❤: I have read the Abstract mam. We can do ...
18    2:04 pm    Mabel Infoziant: I think Vignesh has the data...
19    2:04 pm          Mabel Infoziant: I have sent the abstracts
20    2:06 pm                                         AR❤: Ok mam
21    2:07 pm    AR❤: I have read both the abstract mam. We ca...
22    4:44 pm    Mabel Infoziant: Yes we need to ya about amou...
23    4:48 pm                                      AR❤: Sure mam.
24    8:07 pm                              AR❤: Shall I call mam?
25   10:45 pm    Mabel Infoziant: Hi I was at church couldn’t ...
26   11:52 pm                                     AR❤: It's k mam
27   11:55 pm    AR❤: Just to know the tomorrow plan mam.will ...
28   12:09 pm                AR❤: Mam can u send Vignesh number??
29   12:13 pm    Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...
30   12:23 pm           Mabel Infoziant: I was in a meeting sorry
31   12:25 pm                                AR❤: Can I cal u mam
32   12:26 pm    AR❤: Waiting for u r finalization of rates fo...
33   12:26 pm    AR❤: If we finiliaze I can work with full inv...
34   12:28 pm    AR❤: So what ever may be ..if you think your ...
35   12:28 pm                       AR❤: You deleted this message
36   12:29 pm                                 AR❤: Do the needful
37   12:41 pm    Mabel Infoziant: No ma please hold I am in a ...
38   12:42 pm                                 AR❤: Ok mam thank u
39    7:59 am    Mabel Infoziant: Ramisha we need to talk toda...
40    8:00 am    Mabel Infoziant: Be ready to discuss about th...
41    8:55 am                                       AR❤: Okay mam
42    2:26 pm                                 Mabel Infoziant: ok
43    8:22 pm                                AR❤: Mam are u free?
44    8:40 pm    Mabel Infoziant: Am at church can call very l...
45    8:40 pm    AR❤: Kk mam. I will ask Arun brother. Small d...
46    3:09 pm                                         AR❤: Hi mam
47    3:09 pm                               AR❤: Any updates mam?
48    3:11 pm    Mabel Infoziant: U might have to start on the...
49    3:11 pm    Mabel Infoziant: There is one project that go...
50    3:12 pm                                       AR❤: Kk mam👍🏻

In [29]:
df["Time"]=message[0]

In [31]:
df

        Date                                               Chat        Time
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...    1:42 pm
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name    1:42 pm
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K    1:42 pm
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok    1:42 pm
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...    1:42 pm
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?    1:43 pm
7   05/12/19                             1:43 pm - AR❤: Yes Mam    1:43 pm
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...    1:43 pm
9   05/12/19                            1:43 pm - AR❤: Yeah mam    1:43 pm
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...    1:43 pm
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...    1:43 pm
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...    1:44 pm
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...    1:45 pm
14  05/12/19                      1:48 pm - Mabel Infoziant: ok    1:48 pm
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...    1:48 pm
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...    1:49 pm
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...    2:00 pm
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...    2:04 pm
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...    2:04 pm
20  05/12/19                              2:06 pm - AR❤: Ok mam    2:06 pm
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...    2:07 pm
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...    4:44 pm
23  05/12/19                           4:48 pm - AR❤: Sure mam.    4:48 pm
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?    8:07 pm
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...   10:45 pm
26  08/12/19                         11:52 pm - AR❤: It's k mam   11:52 pm
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...   11:55 pm
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??   12:09 pm
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...   12:13 pm
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...   12:23 pm
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam   12:25 pm
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...   12:26 pm
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...   12:26 pm
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...   12:28 pm
35  09/12/19           12:28 pm - AR❤: You deleted this message   12:28 pm
36  09/12/19                     12:29 pm - AR❤: Do the needful   12:29 pm
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...   12:41 pm
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u   12:42 pm
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...    7:59 am
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...    8:00 am
41  10/12/19                            8:55 am - AR❤: Okay mam    8:55 am
42  12/12/19                      2:26 pm - Mabel Infoziant: ok    2:26 pm
43  15/12/19                     8:22 pm - AR❤: Mam are u free?    8:22 pm
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...    8:40 pm
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...    8:40 pm
46  18/12/19                              3:09 pm - AR❤: Hi mam    3:09 pm
47  18/12/19                    3:09 pm - AR❤: Any updates mam?    3:09 pm
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...    3:11 pm
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...    3:11 pm
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻    3:12 pm

In [33]:
message1=message[1].str.split(":",n=1,expand=True)

In [35]:
message1

                   0                                                  1
1    Mabel Infoziant                     Hi this is Mabel we just spoke
2    Mabel Infoziant                              What’s your full name
3                AR❤                                     Ramisha Rani K
4    Mabel Infoziant                                                 Ok
5    Mabel Infoziant                             ramisharanik@gmail.com
6    Mabel Infoziant                                     Your email Id?
7                AR❤                                            Yes Mam
8    Mabel Infoziant     I will send 2 abstracts for u to start working
9                AR❤                                           Yeah mam
10   Mabel Infoziant                   Give me the list that u have too
11   Mabel Infoziant   Send me cbe office address and phone number I...
12               AR❤    Yeah Mam within Evening I will forward you mam.
13               AR❤   Tomorrow I have to visit the office.yet not I...
14   Mabel Infoziant                                                 ok
15   Mabel Infoziant   send the details of office location once u ge...
16               AR❤   Sure mam. Soon I will share details with you mam
17               AR❤   I have read the Abstract mam. We can do mam. ...
18   Mabel Infoziant   I think Vignesh has the data set will ask him...
19   Mabel Infoziant                          I have sent the abstracts
20               AR❤                                             Ok mam
21               AR❤   I have read both the abstract mam. We can do ...
22   Mabel Infoziant   Yes we need to ya about amount and all other ...
23               AR❤                                          Sure mam.
24               AR❤                                  Shall I call mam?
25   Mabel Infoziant         Hi I was at church couldn’t take your call
26               AR❤                                         It's k mam
27               AR❤   Just to know the tomorrow plan mam.will see t...
28               AR❤                    Mam can u send Vignesh number??
29   Mabel Infoziant           Vignesh ML Infoziant.vcf (file attached)
30   Mabel Infoziant                           I was in a meeting sorry
31               AR❤                                    Can I cal u mam
32               AR❤   Waiting for u r finalization of rates for our...
33               AR❤   If we finiliaze I can work with full involvem...
34               AR❤   So what ever may be ..if you think your are c...
35               AR❤                           You deleted this message
36               AR❤                                     Do the needful
37   Mabel Infoziant   No ma please hold I am in a hot meeting with ...
38               AR❤                                     Ok mam thank u
39   Mabel Infoziant   Ramisha we need to talk today i will call u a...
40   Mabel Infoziant     Be ready to discuss about the ML titles u have
41               AR❤                                           Okay mam
42   Mabel Infoziant                                                 ok
43               AR❤                                    Mam are u free?
44   Mabel Infoziant   Am at church can call very late or tomorrow only
45               AR❤   Kk mam. I will ask Arun brother. Small doubt ...
46               AR❤                                             Hi mam
47               AR❤                                   Any updates mam?
48   Mabel Infoziant     U might have to start on the WhatsApp analysis
49   Mabel Infoziant            There is one project that got committed
50               AR❤                                           Kk mam👍🏻

In [37]:
df["Name"]=message1[0]

In [39]:
df["Chat"]=message1[1]

In [41]:
df

,Date,Chat,Time,Name
1,05/12/19,Hi this is Mabel we just spoke,1:42 pm,Mabel Infoziant
2,05/12/19,What’s your full name,1:42 pm,Mabel Infoziant
3,05/12/19,Ramisha Rani K,1:42 pm,AR❤
4,05/12/19,Ok,1:42 pm,Mabel Infoziant
5,05/12/19,ramisharanik@gmail.com,1:42 pm,Mabel Infoziant
6,05/12/19,Your email Id?,1:43 pm,Mabel Infoziant
7,05/12/19,Yes Mam,1:43 pm,AR❤
8,05/12/19,I will send 2 abstracts for u to start working,1:43 pm,Mabel Infoziant
9,05/12/19,Yeah mam,1:43 pm,AR❤
10,05/12/19,Give me the list that u have too,1:43 pm,Mabel Infoziant
11,05/12/19,Send me cbe office address and phone number I...,1:43 pm,Mabel Infoziant
12,05/12/19,Yeah Mam within Evening I will forward you mam.,1:44 pm,AR❤
13,05/12/19,Tomorrow I have to visit the office.yet not I...,1:45 pm,AR❤
14,05/12/19,ok,1:48 pm,Mabel Infoziant
15,05/12/19,send the details of office location once u ge...,1:48 pm,Mabel Infoziant
16,05/12/19,Sure mam. Soon I will share details with you mam,1:49 pm,AR❤
17,05/12/19,I have read the Abstract mam. We can do mam. ...,2:00 pm,AR❤
18,05/12/19,I think Vignesh has the data set will ask him...,2:04 pm,Mabel Infoziant
19,05/12/19,I have sent the abstracts,2:04 pm,Mabel Infoziant
20,05/12/19,Ok mam,2:06 pm,AR❤
21,05/12/19,I have read both the abstract mam. We can do ...,2:07 pm,AR❤
22,05/12/19,Yes we need to ya about amount and all other ...,4:44 pm,Mabel Infoziant
23,05/12/19,Sure mam.,4:48 pm,AR❤
24,05/12/19,Shall I call mam?,8:07 pm,AR❤
25,08/12/19,Hi I was at church couldn’t take your call,10:45 pm,Mabel Infoziant
26,08/12/19,It's k mam,11:52 pm,AR❤
27,08/12/19,Just to know the tomorrow plan mam.will see t...,11:55 pm,AR❤
28,09/12/19,Mam can u send Vignesh number??,12:09 pm,AR❤
29,09/12/19,Vignesh ML Infoziant.vcf (file attached),12:13 pm,Mabel Infoziant
30,09/12/19,I was in a meeting sorry,12:23 pm,Mabel Infoziant
31,09/12/19,Can I cal u mam,12:25 pm,AR❤
32,09/12/19,Waiting for u r finalization of rates for our...,12:26 pm,AR❤
33,09/12/19,If we finiliaze I can work with full involvem...,12:26 pm,AR❤
34,09/12/19,So what ever may be ..if you think your are c...,12:28 pm,AR❤
35,09/12/19,You deleted this message,12:28 pm,AR❤
36,09/12/19,Do the needful,12:29 pm,AR❤
37,09/12/19,No ma please hold I am in a hot meeting with ...,12:41 pm,Mabel Infoziant
38,09/12/19,Ok mam thank u,12:42 pm,AR❤
39,10/12/19,Ramisha we need to talk today i will call u a...,7:59 am,Mabel Infoziant
40,10/12/19,Be ready to discuss about the ML titles u have,8:00 am,Mabel Infoziant
41,10/12/19,Okay mam,8:55 am,AR❤
42,12/12/19,ok,2:26 pm,Mabel Infoziant
43,15/12/19,Mam are u free?,8:22 pm,AR❤
44,15/12/19,Am at church can call very late or tomorrow only,8:40 pm,Mabel Infoziant
45,15/12/19,Kk mam. I will ask Arun brother. Small doubt ...,8:40 pm,AR❤
46,18/12/19,Hi mam,3:09 pm,AR❤
47,18/12/19,Any updates mam?,3:09 pm,AR❤
48,18/12/19,U might have to start on the WhatsApp analysis,3:11 pm,Mabel Infoziant
49,18/12/19,There is one project that got committed,3:11 pm,Mabel Infoziant
50,18/12/19,Kk mam👍🏻,3:12 pm,AR❤

In [43]:
df=df[["Date","Time","Name","Chat"]]

In [45]:
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Time    50 non-null     object
 2   Name    50 non-null     object
 3   Chat    50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB

In [49]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Inst_\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [50]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [55]:
dataset=df

In [61]:
def sentimentalAnalysis(data,columnName):
    import matplotlib.pyplot as plt
    import seaborn as sns
    "Importing neccessary package"
    from nltk.sentiment.vader import SentimentIntensityAnalyzer
    sid=SentimentIntensityAnalyzer()
    "Deletiing null or empty value"
    data.dropna(inplace=True)
    "Creating respective columns"
    data["scores"]=data[columnName].apply (lambda commentText: sid.polarity_scores(commentText))
    data["compound"]=data["scores"].apply(lambda score_dict: score_dict["compound"])
    data["Negative"]=data["scores"].apply(lambda score_dict: score_dict["neg"])
    data["Positive"]=data["scores"].apply(lambda score_dict: score_dict["pos"])
    data["Neutral"]=data["scores"].apply(lambda score_dict: score_dict["neu"])
    "Creating final pos or neg using compound score"
    data["comp_score"]=data["compound"].apply(lambda c: 'pos' if c>0 else 'neg')
    "Checking how many pos and neg"
    posneg=pd.DataFrame(data["comp_score"].value_counts())
    return posneg,data

In [63]:
pos,data_Senti = sentimentalAnalysis(dataset,columnName="Chat")

In [65]:
pos

            count
comp_score
neg            28
pos            22

In [69]:
data_Senti

,Date,Time,Name,Chat,scores,compound,Negative,Positive,Neutral,comp_score
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [75]:
tfidf=TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm=tfidf.fit_transform(df["Chat"])

In [77]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model=LatentDirichletAllocation(n_components=5, random_state=42)
lda_model.fit(dtm)

LatentDirichletAllocation(n_components=5, random_state=42)

In [81]:
for index, topic in enumerate(lda_model.components_):
    results=([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    print(results)

['number', 'need', 'yes', 'hi', 'just', 'office', 'send', 'details', 'vignesh', 'ml']
['meeting', 'soon', 'ramisha', 'number', 'office', 'students', 'phone', 'yes', 'need', 'ok']
['ask', 'project', 'think', 'read', 'abstract', 'sure', 'kk', 'finiliaze', 'yeah', 'mam']
['soon', 'ask', 'mam', 'office', 'just', 'know', 'church', 'meeting', 'project', 'tomorrow']
['details', 'yes', 'ask', 'mam', 'send', 'church', 'ramisha', 'hi', 'start', 'abstracts']

In [83]:
topic_results=lda_model.transform(dtm)
df["Topic"]=topic_results.argmax(axis=1)

In [85]:
df

,Date,Time,Name,Chat,scores,compound,Negative,Positive,Neutral,comp_score,Topic
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,4
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos,1
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,4
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,2
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos,1
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos,2
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos,1
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos,2
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,2
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,4
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,1
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,2
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos,0
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos,2
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,2
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,4
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,2
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos,3
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos,0
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg,3
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,2
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,2
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos,2
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,0
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg,1
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos,1
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,1
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos,0
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos,2
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos,2
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,3
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos,2
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,4
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,2
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,neg,4
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos,3
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos,2

In [87]:
df["Topic"].value_counts()

Topic
2    16
0    14
1    10
4     6
3     4
Name: count, dtype: int64